// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_CHKv8dlMRIUekeTLtmpQRZI0OWAboQ',
    appId: '1:833062579180:web:8e33fa5624fd8765e0eec9',
    messagingSenderId: '833062579180',
    projectId: 'socialapp-196e7',
    authDomain: 'socialapp-196e7.firebaseapp.com',
    storageBucket: 'socialapp-196e7.appspot.com',
    measurementId: 'G-EK025QM776',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyGGbE6swFb0JzUvTK_9r52T_IMfR-8mE',
    appId: '1:833062579180:android:3fa81840d07daa4fe0eec9',
    messagingSenderId: '833062579180',
    projectId: 'socialapp-196e7',
    storageBucket: 'socialapp-196e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1-6ajM0U8Vh_bbxnEoLr9SOk98RnIzms',
    appId: '1:833062579180:ios:5eb84014c1d2f1ace0eec9',
    messagingSenderId: '833062579180',
    projectId: 'socialapp-196e7',
    storageBucket: 'socialapp-196e7.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq_CHKv8dlMRIUekeTLtmpQRZI0OWAboQ',
    appId: '1:833062579180:web:806dc542074a7bb2e0eec9',
    messagingSenderId: '833062579180',
    projectId: 'socialapp-196e7',
    authDomain: 'socialapp-196e7.firebaseapp.com',
    storageBucket: 'socialapp-196e7.appspot.com',
    measurementId: 'G-T1ZW43J77W',
  );
}
